on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n probanqkoq -g probanqkoqb31e-rg --location "West Europe" --sku Basic --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n probanqkoq --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n probanqkoq --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n probanqkoq --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: probanqkoq.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t probanqkoq.azurecr.io/mekubernetis:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push probanqkoq.azurecr.io/mekubernetis:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_mekubernetis_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep mewebapp | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace mewebapp`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: mewebapp
        container-registry-url: probanqkoq.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: mekubernetisdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: mewebapp
        manifests: |
          manifests/deployment-4.yml
          manifests/service-4.yml
          manifests/ingress-3.yml
        images: |
          probanqkoq.azurecr.io/mekubernetis:${{ github.sha }}
        imagepullsecrets: |
          mekubernetisdockerauth   
